import Navbar from 'react-bootstrap/Navbar'; // Import the Bootstrap Navbar component
import Button from 'react-bootstrap/Button'; // Import the Bootstrap Button component
import Offcanvas from 'react-bootstrap/Offcanvas'; // Import the Bootstrap Offcanvas  component
import React, { useState } from 'react'; // Import the Bootstrap Offcanvas  component
import "../styles/headerStyles.css" // Imports the CSS file for styling Header

//Header component 
function Header() {
    const [show, setShow] = useState(false); //state setting function for offcanvas
    const handleClose = () => setShow(false); //handling function for closing offcanvas
    const handleShow = () => setShow(true);   //handling function for showing offcanvas

    return (
        <Navbar className="header-container">
            <Navbar.Brand>HANGMAN</Navbar.Brand>
            <Button variant="primary" onClick={handleShow}> 
                ?
            </Button>
            <Offcanvas show={show} onHide={handleClose} > 
                <Offcanvas.Header closeButton>
                    <Offcanvas.Title>Rules</Offcanvas.Title> 
                </Offcanvas.Header>
                <Offcanvas.Body >
                    The game is played by guessing a secret word generated by the computer. The word is represented by a series of underscores, with each underscore representing a letter of the word.
                    The player starts guessing letters one at a time. If the guessed letter is in the secret word, all occurrences of that letter are revealed in the word. If the guessed letter is not in the word, a part of the hangman's body is drawn on the screen.
                    The game continues until either the player successfully guesses the entire word or the hangman is completely drawn.
                    The player has a limited number of incorrect guesses before the game ends in failure. In traditional hangman, the player is allowed 11 incorrect guesses before the game ends.
                    The player is not allowed to guess the same letter twice.
                    The player can choose to give up at any time, forfeiting the game.
                    The game can be played alone or with multiple players taking turns guessing the secret word.
                </Offcanvas.Body>
            </Offcanvas>
        </Navbar>
    )
}

export default Header; //exports for import